# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "noir"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

mainSection = ["CV", "Publications"]

defaultBackgroundImage = "img/background.jpg"

[homepage]
  layout = "background"
  homepageImage = "img/background_mountain.jpg"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/publications"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background


enableSearch = true
enableCodeCopy = true

disableImageOptimization = false
disableTextInHeader = false

defaultBackgroundImage = "/img/ocean.jpg"
defaultFeaturedImage = "/img/ocean.jpg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

#mainSections = ["posts", "publications"]
# robots = ""

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

#homepage.layout = "background" # valid options: page, profile, hero, card, background, custom
#homepage.homepageImage = "img/background.jpg" # used in: hero, and card
#homepage.showRecent = true
#homepage.showRecentItems = 3
#homepage.showMoreLink = true
#homepage.showMoreLinkDest = "/blowfish_artist/posts"
#homepage.cardView = true
#homepage.cardViewScreenWidth = false
#homepage.layoutBackgroundBlur = true # only used when layout equals background


[article]
  showDate = false
  #showViews = true
  #showLikes = true
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false 
  showAuthorsBadges = false 
  showWordCount = false
  showSummary = false

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false
